package com.compiler;
/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 5.0 */
public interface eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTMAINCLASS = 1;
  public int JJTTYPEDECLARATION = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTCLASSEXTENDSDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTPREDECL = 6;
  public int JJTPOSTDECL = 7;
  public int JJTFORMALPARAMETERLIST = 8;
  public int JJTFORMALPARAMETER = 9;
  public int JJTFORMALPARAMETERREST = 10;
  public int JJTTYPE = 11;
  public int JJTARRAYTYPE = 12;
  public int JJTLONGARRAYTYPE = 13;
  public int JJTBOOLEANTYPE = 14;
  public int JJTINTEGERTYPE = 15;
  public int JJTLONGTYPE = 16;
  public int JJTSTATEMENT = 17;
  public int JJTVARDECLARATION = 18;
  public int JJTBLOCK = 19;
  public int JJTASSIGNMENTSTATEMENT = 20;
  public int JJTARRAYASSIGNMENTSTATEMENT = 21;
  public int JJTIFSTATEMENT = 22;
  public int JJTWHILESTATEMENT = 23;
  public int JJTPRINTSTATEMENT = 24;
  public int JJTEXPRESSION = 25;
  public int JJTANDEXPRESSION = 26;
  public int JJTCOMPAREEXPRESSION = 27;
  public int JJTPLUSEXPRESSION = 28;
  public int JJTTIMESEXPRESSION = 29;
  public int JJTARRAYLOOKUP = 30;
  public int JJTARRAYLENGTH = 31;
  public int JJTMESSAGESEND = 32;
  public int JJTEXPRESSIONLIST = 33;
  public int JJTEXPRESSIONREST = 34;
  public int JJTPRIMARYEXPRESSION = 35;
  public int JJTLONGLITERAL = 36;
  public int JJTINTEGERLITERAL = 37;
  public int JJTTRUELITERAL = 38;
  public int JJTFALSELITERAL = 39;
  public int JJTIDENTIFIER = 40;
  public int JJTTHISEXPRESSION = 41;
  public int JJTARRAYALLOCATIONEXPRESSION = 42;
  public int JJTALLOCATIONEXPRESSION = 43;
  public int JJTNOTEXPRESSION = 44;
  public int JJTBRACKETEXPRESSION = 45;


  public String[] jjtNodeName = {
    "Start",
    "MainClass",
    "TypeDeclaration",
    "ClassDeclaration",
    "ClassExtendsDeclaration",
    "MethodDeclaration",
    "PreDecl",
    "PostDecl",
    "FormalParameterList",
    "FormalParameter",
    "FormalParameterRest",
    "Type",
    "ArrayType",
    "LongArrayType",
    "BooleanType",
    "IntegerType",
    "LongType",
    "Statement",
    "VarDeclaration",
    "Block",
    "AssignmentStatement",
    "ArrayAssignmentStatement",
    "IfStatement",
    "WhileStatement",
    "PrintStatement",
    "Expression",
    "AndExpression",
    "CompareExpression",
    "PlusExpression",
    "TimesExpression",
    "ArrayLookup",
    "ArrayLength",
    "MessageSend",
    "ExpressionList",
    "ExpressionRest",
    "PrimaryExpression",
    "LongLiteral",
    "IntegerLiteral",
    "TrueLiteral",
    "FalseLiteral",
    "Identifier",
    "ThisExpression",
    "ArrayAllocationExpression",
    "AllocationExpression",
    "NotExpression",
    "BracketExpression",
  };
}
/* JavaCC - OriginalChecksum=df98f54e01f5ee3fa08b84024bbdeca5 (do not edit this line) */
